staging-settings:
  user-workflow:
    workflow-name: "opengrant-health-monitoring"
  workflow-artifacts:
    workflow-path: "./src/index.ts"
    config-path: "./config.json"
    secrets-path: "../secrets.yaml"

production-settings:
  user-workflow:
    workflow-name: "opengrant-health-monitoring"
  workflow-artifacts:
    workflow-path: "./src/index.ts"
    config-path: "./config.json"
    secrets-path: "../secrets.yaml"
